### ISSUE TITLE
not working with latest version of Iotivity-Lite

### ISSUE THREAD

**Issue by InfiRR** [plgd-dev/device#171] opened 2021-04-17 16:53 UTC
Hi,

Using your SDK I was able to check when a new device ( Iotivity-Lite ) was online on the network and proceed with a secured onboard ( Iotivity-Lite already had the certificate from PLGD-Bundle ).

My current setup worked using :
	github.com/plgd-dev/cloud v1.1.2
	github.com/plgd-dev/kit v0.0.0-20210322121129-fa0d31a13679
	github.com/plgd-dev/sdk v0.0.0-20210219105030-130a058ac50e

From git:
        commit b6f5d62a69d00ac241dd19865c27070f1a3a6d98 (HEAD -> plgd.dev, origin/plgd.dev)
        Merge: ce36c87a 14570f6e
        Author: Jozef Kralik <jozef.kralik@kistler.com>
        Date:   Fri Feb 26 13:05:58 2021 +0000
        
            Merge branch 'fixSegFault' into plgd.dev

If using the Iotivity-Lite
      commit 5afd227c6e2d18287890f0dee8d6e3a0103f506d (HEAD -> master, origin/static-message-buffers, origin/master, origin/HEAD)
      Author: Alexandru Tiniuc <a.tiniuc@cascoda.com>
      Date:   Mon Mar 22 16:13:41 2021 +0000
      
          clarify OC_REQUEST_HISTORY_SIZE
      

I am no longer capable to decode the CBOR during SDK device discovery failing in : Plgd-kit codec.go line 38

Is this something that PLGD team is aware of?

Please advise if more info is required or a project to reproduce

**Comment by jkralik** [comment] 2021-04-17 18:48
Hi @InfiRR

The Iotivity-Lite master branch contains release jakarta which brings end2end encryption via OSCORE(https://tools.ietf.org/html/rfc8613) and it is by default enabled. Cloud and SDK doesn't support the feature for now so you need to disable it via parameter `OSCORE=0`  eg `make OSCORE=0 SECURE=1 ... `
After that you will be able to discover device.  Maybe there will be issue with own - I need to check it.

**Comment by InfiRR** [comment] 2021-04-19 07:35
I still obtain the same result.

If i get all devices ( 1 available in my network) using the SDK it will get:

{"level":"error","ts":1618817394.0644252,"caller":"log/log.go:71","msg":"decoding Path: \nFormat: application/vnd.ocf+cbor\n failed: decoding failed for the message 00d594081aac2bac on ","stacktrace":"github.com/plgd-dev/kit/log.Error\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/kit/log/log.go:71\ngithub.com/plgd-dev/sdk/local.(*Client).GetDevices.func1\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/sdk/local/getDevices.go:27\ngithub.com/plgd-dev/sdk/local.(*discoveryOwnershipsHandler).Error\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/sdk/local/getDevices.go:239\ngithub.com/plgd-dev/sdk/local/core.(*ownershipHandler).Error\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/sdk/local/core/getOwnerships.go:53\ngithub.com/plgd-dev/sdk/local/core.handleDiscoverOwnershipResponse.func1\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/sdk/local/core/discoverDeviceOwnership.go:82\ngithub.com/plgd-dev/go-coap/v2/udp.(*Server).DiscoveryRequest.func1\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/udp/discover.go:64\ngithub.com/plgd-dev/go-coap/v2/udp.(*Server).getOrCreateClientConn.func2\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/udp/server.go:298\ngithub.com/plgd-dev/go-coap/v2/udp/client.NewObservationHandler.func1\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/udp/client/clientobserve.go:40\ngithub.com/plgd-dev/go-coap/v2/udp/client.(*ClientConn).handleBW.func1\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/udp/client/clientconn.go:437\ngithub.com/plgd-dev/go-coap/v2/net/blockwise.(*BlockWise).processReceivedMessage\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/net/blockwise/blockwise.go:647\ngithub.com/plgd-dev/go-coap/v2/net/blockwise.(*BlockWise).handleReceivedMessage\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/net/blockwise/blockwise.go:530\ngithub.com/plgd-dev/go-coap/v2/net/blockwise.(*BlockWise).Handle\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/net/blockwise/blockwise.go:482\ngithub.com/plgd-dev/go-coap/v2/udp/client.(*ClientConn).handleBW\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/udp/client/clientconn.go:429\ngithub.com/plgd-dev/go-coap/v2/udp/client.(*ClientConn).handle\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/udp/client/clientconn.go:463\ngithub.com/plgd-dev/go-coap/v2/udp/client.(*ClientConn).Process.func1\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/udp/client/clientconn.go:488\ngithub.com/plgd-dev/go-coap/v2/udp.glob..func6.1\n\tC:/Personal_Work/git/xr-obt/vendor/github.com/plgd-dev/go-coap/v2/udp/server.go:54"}

The ownership does no longer comes filled.


If I try to get the device from the event of the online device and then try to get it using the SDK I get:

2021/04/19 08:33:23 decoding Path: 
Format: application/vnd.ocf+cbor
 failed: decoding failed for the message 102dec2cfebcaf46 on 


Is there a specific version of the SDK that I should use?

**Comment by ondrejtomcik** [comment] 2021-04-19 10:32
@InfiRR we always try to keep master branches of both projects compatible. IoTivity-Lite develops features in feature branches named by OCF releases. The latest release Jakarta was just recently merged to the master, where is the new functionality which is not compatible with our SDK. We will look into it today and give you feedback ASAP.

**Comment by jkralik** [comment] 2021-04-19 12:46
@InfiRR You need to cleanup build with `make clean && make cleanall` commands before you run `make OSCORE=0 SECURE=1 ...`. I tested it with current master sdk (4fa102b7c2b6a5d8944b18db578c0c9109d2c118) and discovery works.

**Comment by InfiRR** [comment] 2021-04-20 07:20
hi

Still can't put it to fully work:

using latest iotivity-lite and executing as advised "make cloud_server TCP=1 SECURE=1 CLOUD=1 OSCORE=0"

The problem regarding the decoding of CBOR is solved.

but trying to ownDevice+onboardDevice results in:
(Internal) cannot get udp/tcp secure address: [cannot connect to coaps://[fe80::a47c:4876:4520:798b%Ethernet]:37081: handshake error: context deadline exceeded cannot connect to coaps+tcp://[fe80::a47c:4876:4520:798b%Ethernet]:42183: cannot dial to url coaps+tcp://[fe80::a47c:4876:4520:798b%Ethernet]:42183: scheme coaps+tcp not supported cannot connect to***

Using the same setup with a previous iotivity it works at the first try. Both iotivities have the certificate placed in the pki directory.

using:
	github.com/plgd-dev/kit v0.0.0-20210322121129-fa0d31a13679
	github.com/plgd-dev/sdk v0.0.0-20210401090232-4fa102b7c2b6


Is there some additional steps/configuration required?

**Comment by ondrejtomcik** [comment] 2021-04-20 07:43
To unblock your work @InfiRR switch to the `plgd.dev` branch. Jakarta release is not yet finished, we are working on two new features following the spec change requests.

We will be compatible with the Jakarta before the official OCF/IoTivity release, but currently, our focus is somewhere else.
Is there something concrete you need from the master branch that is not merged to the plgd.dev branch?

FYI, plgd.dev branch doesn't contain custom commits.  We use this branch if we did some bugfixes which were not yet merged to the master but we have them in plgd.dev.

**Comment by InfiRR** [comment] 2021-04-20 13:40
Thanks for the feedback. A request was made for the local team working with Iotivity to check the feasibility of the request.

Please close this issue.

**Comment by ondrejtomcik** [comment] 2021-04-21 06:56
@InfiRR we will close this issue when it will work again. Issue is valid.
Thanks for reporting it!

**Comment by jkralik** [comment] 2021-10-08 08:50
The issue is fixed by https://github.com/plgd-dev/device/pull/192

**Closed by jkralik** 2021-10-08 08:50 UTC
